language: python
python:
- '2.7'
- '3.7'
install:
- pip install codecov
script:
- python -m unittest discover -v ./ci_play/
- coverage run ./ci_play/test.py
after_success: bash <(curl -s https://codecov.io/bash)

addons:
 ssh_knows_hosts: moon.scs.ryerson.ca

before_install:
- openssl aes-256-cbc -K $encrypted_4204cd8d5f47_key -iv $encrypted_4204cd8d5f47_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval"$(ssh-agent -s)"
- chmod600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

# setup ENV ($) variables in the web interface
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet 
     ${TRAVIS_BUILD_DIR}/HelloWorld/index.html      
     ${DEPLOY_USER}@${DEPLOY_SERVER}:/home/avm/courses/cps847/${DEPLOY_USER}
  on:
    branch: master
